# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: "Richard Westenra | Web designer &amp; front-end developer"
description: "I make websites. Not shit websites. Good websites."
author:
  name: Richard Westenra
  email: rjwestenra@gmail.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg',
          '**.ico', 'node_modules']

include: ['.htaccess','**.ico','sitemap.xml', 'CNAME']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: true

permalink: :title/

relative_permalinks: false

liveUrl: "http://richardwestenra.com/"